### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / DELIB_MEC

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#10]
Dans le [standard CNIG v2024][(https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024](https://cnig.gouv.fr/IMG/pdf/231220_standard_cnig_plu_v2024-01.pdf)), la désignation de DELIB_MEC n'est pas `delib` mais `delib_mec`

![image](https://github.com/user-attachments/assets/2a180370-d533-40f7-9bdb-e521647a6ea2)

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/238c4bda956364679b94d3ea3cbeb899c56bc190
