### ISSUE TITLE
 Pescriptions 18-15 et 18-16 absentes du validateur CNIG V2024-01 

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#2]
PRESCRIPTION.STYPEPSC : les sous-codes 15 et 16 des prescriptions 18 (OAP) : 18-15 et 18-16 semblent absents du [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024).

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/00a33b21a5ad800acc8e1a425e88d39d918c1f1e
