### ISSUE TITLE
Destinations 47 et 55 absentes du validateur CNIG V2024-01

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#3]
ZONEURBA.DESTOUI (idem pour DESTCDT et DESTNON) : les codes 47 : "lieux de culte" et 55 : "cuisine dédiée à la vente en ligne" semblent absents du [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024).

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/00a33b21a5ad800acc8e1a425e88d39d918c1f1e
