### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / NOMPROC est obligatoire

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#5]
Le [standard CNIG PLU/CC v2024](https://cnig.gouv.fr/IMG/pdf/231220_standard_cnig_plu_v2024-01.pdf) indique que les fichiers du répertoire  0_Procedure respectent la dénomination normalisée : 

![image](https://github.com/user-attachments/assets/1a71be8a-e6ca-416f-a099-fdc177f0c21c)

**\<NOMPROC>** correspond au code ProcedureUrbaType et n'est pas facultatif.

[ ] corriger dans le [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024) le caractère facultatif de \<NOMPROC> pour les fichiers : 
- ARRETE_DUP
- ARRETE_OBJECTIFS_MODALITES
- AVIS_EVAL_ENV
- AVIS_PPA
- AUTRES_PIECES
- DECISION_DECLARATION_PROJET
- DECISION_EVAL_ENV
- DECRET_DUP
- DELIB_ARRET
- DELIB_DEBAT_PADD
- DELIB_DECLARATION_PROJET
- DELIB_OBJECTIF_MODALITES

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/238c4bda956364679b94d3ea3cbeb899c56bc190
