### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / DECRET_DUP

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#6]
Une coquille s'est glissée dans le [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024)

[ ] Dans "Organisation des fichiers" remplacer DECRET_SUP par **DECRET_DUP**

![image](https://github.com/user-attachments/assets/d4740899-5415-438e-aa3a-fc17f68e6ac9)

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/238c4bda956364679b94d3ea3cbeb899c56bc190
