### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / ARRETE_MAJ_ANNEXES et ARRETE_MEC

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#7]
Dans le [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024), les désignations de ARRETE_MAJ_ANNEXES et ARRETE_MEC ne sont pas `arrete` et `arrete`

![image](https://github.com/user-attachments/assets/37a5725e-fcbe-4d70-99f1-f0c317f61cde)

mais  `arrete_maj_annexes` et  `arrete_mec`

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/238c4bda956364679b94d3ea3cbeb899c56bc190
