### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / ARRETE_OBJECTIFS_MODALITES

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#8]
Dans le [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024)
les désignations `arrete_objectifs_modalites` et `delib_objectifs_modalites`
n'admettent pas de `_et` facultatif :
 
![image](https://github.com/user-attachments/assets/d3ecbe0a-a645-4e02-b758-ba9900775511)

![image](https://github.com/user-attachments/assets/86359e3e-dbcd-4ad7-ae0a-94060c1ad11a)

**Comment by floriancerizay** [comment]
corrigé dans : https://github.com/IGNF/validator-config-gpu/commit/137c6705d29e922cdd6f546a8e34ae945c79572a
