### ISSUE TITLE
Validateur CNIG_PLU_2024 / répertoire 0_Procedure / AVIS_EVAL_ENV

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [IGNF/validator-config-gpu#9]
Pour `AVIS_EVAL_ENV` et `DECISION_EVAL_ENV` le [validateur CNIG V2024-01](https://www.geoportail-urbanisme.gouv.fr/standard/cnig_PLU_2024) admet les désignations `avis_EE` et `decision_EE` qui ne sont pas prévues par le [standard CNIG v2024](https://cnig.gouv.fr/IMG/pdf/231220_standard_cnig_plu_v2024-01.pdf).

![image](https://github.com/user-attachments/assets/60d88dd3-d87d-4e75-9b10-14d6966cb556)

![image](https://github.com/user-attachments/assets/dac37273-6678-4081-a453-4db73ecf35bc)

**Comment by floriancerizay** [comment]
corrigé dans https://github.com/IGNF/validator-config-gpu/commit/137c6705d29e922cdd6f546a8e34ae945c79572a
